# Generated by Django 3.2.9 on 2022-03-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_labprofile_operatingsystem_ostemplate'),
        ('users', '0004_rename_student_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_course', to='lab.course', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
