# Generated by Django 3.2.9 on 2022-06-10 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0017_auto_20220405_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], default='cash', max_length=16, verbose_name='Payment Method')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('ordered', 'ordered'), ('done', 'done')], default='draft', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False, verbose_name='Invoice Sent')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment Received')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Payment Amount')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Discount %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Discount Amount')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('closed', 'closed')], default='draft', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.booking', verbose_name='Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Item Cancelled')),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('done', 'done'), ('ordered', 'ordered'), ('cancelled', 'cancelled')], default='draft', max_length=100, no_check_for_status=True, verbose_name='Status')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.cart', verbose_name='Cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.course', verbose_name='Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
