# Generated by Django 3.2.9 on 2022-01-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20220110_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.difficulty', verbose_name='Difficulty'),
        ),
    ]
