# Generated by Django 3.2.9 on 2022-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
