# Generated by Django 3.2.9 on 2022-01-10 08:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220110_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
