# Generated by Django 3.2.9 on 2022-01-24 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0003_auto_20220124_0610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriberStatus',
            new_name='SubscriberCourseStatus',
        ),
        migrations.AlterModelOptions(
            name='subscribercoursestatus',
            options={'ordering': ['-created'], 'verbose_name': 'SubscriberCourseStatus', 'verbose_name_plural': 'SubscriberCourseStatus'},
        ),
    ]
