# Generated by Django 3.2.9 on 2022-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
