# Generated by Django 3.2.9 on 2022-01-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor'),
        ('lab', '0005_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instructor', verbose_name='Instructor'),
        ),
    ]
