# Generated by Django 3.2.9 on 2022-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20220207_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=250, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
