# Generated by Django 3.2.9 on 2022-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20220207_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.CharField(max_length=250, null=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.CharField(max_length=250, null=True, verbose_name='Overview'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(max_length=250, null=True, verbose_name='Prerequisites'),
        ),
    ]
