# Generated by Django 3.2.9 on 2022-03-27 18:01

from django.db import migrations, models
import generic.constants


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20220228_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=generic.constants.image_file_path, verbose_name='Course Banner'),
        ),
    ]
