# Generated by Django 3.2.9 on 2022-03-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='banner',
        ),
    ]
