# Generated by Django 3.2.9 on 2022-04-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_labprofile_operatingsystem_ostemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.CharField(default=1, max_length=250, verbose_name='Overview'),
            preserve_default=False,
        ),
    ]
